name: html-escape-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/html-escape/__tests__/*.test.js'
      - 'packages/html-escape/src/*.ts'
  push:
    branches:
      - main
    paths:
      - 'packages/html-escape/__tests__/*.test.js'
      - 'packages/html-escape/src/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build -w '@saekitominaga/string-escape-html'
      - run: npm run test -w '@saekitominaga/string-escape-html'

      - uses: coverallsapp/github-action@2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
