name: paapi-item-image-url-parser-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/paapi-item-image-url-parser/__tests__/*.test.js'
      - 'packages/paapi-item-image-url-parser/src/*.ts'
  push:
    branches:
      - main
    paths:
      - 'packages/paapi-item-image-url-parser/__tests__/*.test.js'
      - 'packages/paapi-item-image-url-parser/src/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm test -w '@w0s/paapi-item-image-url-parser'

      - uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
