name: paapi-item-image-url-parser-lint
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/paapi-item-image-url-parser/__tests__/*.test.js'
      - 'packages/paapi-item-image-url-parser/src/*.ts'
  push:
    branches:
      - main
    paths:
      - 'packages/paapi-item-image-url-parser/__tests__/*.test.js'
      - 'packages/paapi-item-image-url-parser/src/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint -w '@saekitominaga/paapi-item-image-url-parser'
